# fly.toml app configuration file generated for hoodhomes on 2025-10-29T18:02:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hoodhomes"
primary_region = "lhr"

[build]

[deploy]
release_command = "python manage.py migrate --noinput"

[env]
PORT = "8000"

[processes]
app = "gunicorn config.wsgi:application --bind 0.0.0.0:8000"


[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "4gb"
cpu_kind = "shared"
cpus = 4



[[statics]]
guest_path = "/code/static"
url_prefix = "/static/"
