# Generated by Django 5.2.2 on 2025-10-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
